name: Telemetry All

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest stable
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Lint
        uses: actions-rs/clippy-check@v1.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features -- -D warnings

      - name: Check code style
        uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: --all -- --check

      - name: Build lib
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build

      - name: Test lib
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test

      - name: Build debug tool
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --bin makair_telemetry --features=build-binary --release

      - name: Build documentation
        uses: actions-rs/cargo@v1.0.1
        with:
          command: doc

      - name: Prepare documentation to be hosted
        run: |
          cp .github/documentation_index.html target/doc/index.html
          tar czvf doc.tar.gz target/doc/

      - name: Archive binary
        uses: actions/upload-artifact@v1
        with:
          name: makair_telemetry
          path: target/release/makair_telemetry

      - name: Archive documentation
        uses: actions/upload-artifact@v1
        with:
          name: doc
          path: doc.tar.gz

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/master'
        with:
          BRANCH: gh-pages
          FOLDER: target/doc/
          TARGET_FOLDER: ./
